on: [push, pull_request]

jobs:

  tests:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        php-version: ['7.2', '7.3', '7.4', '8.0', '8.1', '8.2', '8.3', '8.4']

    steps:
      - uses: actions/checkout@v4
      - run: php -v
      - run: php -m
      - run: composer --version
      - run: composer install
      - run: php vendor/bin/phpunit --bootstrap tests/bootstrap.php tests
